### ISSUE TITLE
Single macos vs all domain-joined macOS systems

### ISSUE THREAD

**Issue by scottctaylor12** [XMCyber/MacHound#1]
Neat project @XMCyber! 
I've been playing with MacHound and noticed that my output.json data is limited to the macOS system it was ran on. Looking through the introductory blogpost and source code, it looks like this expected behavior. SharpHound will enumerate all of the Users and Computers, but I realize macOS is a different beast when it comes to domain joining them. 
So I just wanted to double check, can MacHound query Active Directory for ALL domain joined macOS systems and dump them in the output.json after execution?

**Comment by zur250** [comment]
Hi @scottctaylor12 .
Theoretically you can perform some queries using ldap from the mac machine in order to collect all domain joined macOS system. Currently this type of feature is not supported.

**Comment by ronymunitz** [comment]
Hi @scottctaylor12,

Machound cannot query remote MacOS machines, as Apple does not supply any API for doing that. MacHound must be executed on each machine separately and will only collect local information. MacHound must also be executed as an enrichment tool for an existing Bloodhound database of your Active Directory.

I can suggest a couple of way to collect MacHound information across multiple machines, both requiring either an MDM solution, or remote SSH enabled (which is less recommended for security reasons) to remotely download and execute MacHound on each MacOS machine separately:

1. Creating an file share (SMB or such) on the Ingestor-running machine and redirecting the MacHound collector output to that folder. Remember to give each output file a unique name to avoid data loss.

2. I have started working on a server-client architecture for MacHound in which the Ingestor will have a REST API server that the collector will listen for incoming JSON files from the collector.

Thank you,
Rony

**Comment by scottctaylor12** [comment]
Thanks for the quick responses! What you're saying completely makes sense. A file share mounted to all macOS systems could be a quick-win solution. If you release a macOS configuration data exfiltration C2 (REST API server example), I would definitely be interested in checking that out :)
Again, neat project and happy to see macOS getting some more love.
